export enum Urls {
    'auth' = 'auth',
    'token' = 'token',
    'login' = 'login',
    'logout' = 'logout',
    'error' = 'error',
    'dashboard' = 'dashboard',
    'user' = 'user',
    'list' = 'list',
    'chart' = 'chart',
    'status' = 'status',
    'top_performers' = 'top-performers',
    'performance' = 'performance',
    'project' = 'project',
    'create' = 'create',
    'update' = 'update',
    'view' = 'view',
    'delete' = 'delete',
    'task' = 'task'
}
