export enum UserType {
    LOGIN = 'LOGIN',
    LOGIN_SUCCESS = 'LOGIN_SUCCESS',
    LOGIN_CANCEL = 'LOGIN_CANCEL',

    USER_DETAILS = 'USER_DETAILS',
    USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS',
    USER_DETAILS_CANCEL = 'USER_DETAILS_CANCEL',

    USER_LIST = 'USER_LIST',
    USER_LIST_SUCCESS = 'USER_LIST_SUCCESS',
    USER_LIST_CANCEL = 'USER_LIST_CANCEL',

    LOGOUT = 'LOGOUT',
    LOGOUT_SUCCESS = 'LOGOUT_SUCCESS',
    LOGOUT_CANCEL = 'LOGOUT_CANCEL'
}